### ISSUE TITLE
Profile - updates to open charm and bundle cards

### ISSUE THREAD

**Issue by spencerbygraves** [juju/juju-gui#3460]
After our [discussion about links](https://github.com/juju/juju-gui/issues/3438) and trying various solutions, we have slightly updated the open card design for charms and bundles.

**Closed charm row**

- [x] Charm title to be a blue link, underline on hover
- [x] Tags to be #666666, blue underline on hover

**Closed bundle row**

- [x] Bundle title to be a blue link, underline on hover

**Open charm card**

- [x] Card padding 16px top and bottom
- [x] Charm title to change to 20px blue link, underline on hover
- [x] Tags to be #666666, blue underline on hover
- [x] trusty, xenial, Writeable, Readable and current release should be regular #111111 text
- [x] All other links should be blue, underline on hover
- [x] Remove padding under both the Writeable and Readable titles

**Open bundle card**

- [x] Card padding 16px top and bottom
- [x] Bundle title to change to 20px blue link, underline on hover
- [x] Writeable, Readable, machine number, unit number and current release should be regular #111111 text
- [x] All other links should be blue, underline on hover
- [x] Remove padding under both the Writeable and Readable titles

**Charms**
![image](https://user-images.githubusercontent.com/9105999/35859289-63353db2-0b37-11e8-8965-6ab2d4848d84.png)

**Bundles**
![image](https://user-images.githubusercontent.com/9105999/35859335-8d22f380-0b37-11e8-8a0b-30494e98f9b4.png)
